// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrp5NFCoB3usw3sONpHIsJhJ-6QlItj_M',
    appId: '1:744739874879:web:58df6fe241db863956308a',
    messagingSenderId: '744739874879',
    projectId: 'chat-app-27921',
    authDomain: 'chat-app-27921.firebaseapp.com',
    storageBucket: 'chat-app-27921.appspot.com',
    measurementId: 'G-45S0Z3F4M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3afw9AcJt_vydPzuOnvkDbN5OKwCHA3c',
    appId: '1:744739874879:android:fce9c0143bb714a356308a',
    messagingSenderId: '744739874879',
    projectId: 'chat-app-27921',
    storageBucket: 'chat-app-27921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB47fvZWbY4vQoiIeSXoV-30lSwVg7tHek',
    appId: '1:744739874879:ios:ffc4269e8cef5b0156308a',
    messagingSenderId: '744739874879',
    projectId: 'chat-app-27921',
    storageBucket: 'chat-app-27921.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB47fvZWbY4vQoiIeSXoV-30lSwVg7tHek',
    appId: '1:744739874879:ios:ffc4269e8cef5b0156308a',
    messagingSenderId: '744739874879',
    projectId: 'chat-app-27921',
    storageBucket: 'chat-app-27921.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrp5NFCoB3usw3sONpHIsJhJ-6QlItj_M',
    appId: '1:744739874879:web:93f398f54d1c42f856308a',
    messagingSenderId: '744739874879',
    projectId: 'chat-app-27921',
    authDomain: 'chat-app-27921.firebaseapp.com',
    storageBucket: 'chat-app-27921.appspot.com',
    measurementId: 'G-TCL2E8NXNY',
  );
}
